[build]
  command = "npm run build:prod"
  publish = "out"

[build.environment]
  NEXT_PUBLIC_API_URL = "http://anneyelina.duckdns.org"
  NEXT_PUBLIC_UPLOADS_URL = "http://anneyelina.duckdns.org/uploads"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[redirects]]
  from = "/uploads/*"
  to = "http://anneyelina.duckdns.org/uploads/:splat"
  status = 200
  force = true

[[headers]]
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*" 