[build]
  base = "frontend"
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Remove the redirect rule that's causing issues
# [[redirects]]
#   from = "/*"
#   to = "/index.html"
#   status = 200 

[build.environment]
  NEXT_USE_NETLIFY_EDGE = "true"
  NODE_VERSION = "18"
  NEXT_TELEMETRY_DISABLED = "1" 