[build]
  command = "npm run build"
  publish = "out"

[build.environment]
  NEXT_PUBLIC_API_URL = "http://anneyelina.duckdns.org"
  NEXT_PUBLIC_UPLOAD_URL = "http://anneyelina.duckdns.org/uploads"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 