[build]
  command = "npm run build"
  publish = "out"

[build.environment]
  NETLIFY_NEXT_PLUGIN_SKIP = "true"
  NEXT_PUBLIC_API_URL = "https://anneyelina.duckdns.org"
  NEXT_PUBLIC_UPLOADS_URL = "https://anneyelina.duckdns.org/uploads"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 